<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="$(AspireVersion)"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(NetCoreTestVersion)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UserSecretsId>df5f361f-692c-4438-a33f-9f6b45342370</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Kafka" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleProducer\SimpleProducer.csproj" />
    <ProjectReference Include="..\SimpleConsumer\SimpleConsumer.csproj" />
  </ItemGroup>

</Project>
