parameters:
  name: ''
  vmImage: ''
  timeoutInMinutes: 120

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    
    steps:
      - script: dotnet --info
        displayName: 'Show dotnet SDK info'
          
      - script: dotnet restore
        displayName: 'Restore packages'
          
      - script: dotnet build -c Release
        displayName: 'Build'
          
      - script: dotnet test -c Release --no-build --logger:trx
        displayName: 'Run tests'
          
      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'
          testRunTitle: '${{ parameters.name }}'
          mergeTestResults: true
        condition: succeededOrFailed()
          
      - script: dotnet pack -c Release --no-build -o $(Build.ArtifactStagingDirectory)/nuget
        displayName: 'Create packages'
          
      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/nuget'
          ArtifactName: 'nuget'
          publishLocation: 'Container'