# Nightly build task for Akka.Streams.Kafka
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - dev

variables:
  - group: nugetKeys

jobs:
  - job: Nightly
    pool:
      vmImage: windows-latest
      demands: Cmd
    steps:
      - script: dotnet restore
        displayName: 'Restore packages'

      # Update version from RELEASE_NOTES.md
      - script: .\version.ps1
        displayName: 'Update version from RELEASE_NOTES.md'

      # Update version with beta suffix
      - script: |
          $timestamp = (Get-Date).ToUniversalTime().ToString("yyyyMMddHHmm")
          $suffix = "beta$timestamp"
          echo "##vso[task.setvariable variable=VersionSuffix]$suffix"
        displayName: 'Generate version suffix'
        powershell: true

      # Pack with version suffix
      - script: dotnet pack -c Release --version-suffix $(VersionSuffix) -o $(Build.ArtifactStagingDirectory)/nuget
        displayName: 'Create packages'

      - script: dotnet nuget push "$(Build.ArtifactStagingDirectory)\nuget\*.nupkg" --api-key $(nightlyKey) --source $(nightlyUrl) --skip-duplicate
        displayName: 'Publish to internal feed'
