<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Generated.props', '$(MSBuildThisFileDirectory)'))" />
  <PropertyGroup>
    <Copyright>Copyright © 2015-2025 Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <Tags>akka, akka.streams, kafka, akkadotnet, akka streams, akka.streams.kafka</Tags>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <!-- Visual Studio C# settings -->
    <NetFrameworkTestVersion>net472</NetFrameworkTestVersion>
    <NetStandardLibVersion>netstandard2.0</NetStandardLibVersion>
    <NetLibVersion>net6.0</NetLibVersion>
    <NetCoreTestVersion>net6.0</NetCoreTestVersion>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Akka.Event" />
  </ItemGroup>
  <!-- GitHub SourceLink -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <!-- NuGet package properties -->
  <PropertyGroup>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageProjectUrl>https://github.com/akkadotnet/Akka.Streams.Kafka</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
